services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Domain\:
        resource: '../src/Domain/*'

    App\Application\:
        resource: '../src/Application/*'

    App\Infrastructure\:
        resource: '../src/Infrastructure/*'

    # Repository binding
    App\Domain\Repository\MiddoRepositoryInterface:
        class: App\Infrastructure\Repository\InMemoryMiddoRepository
